// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchoolWebAPI.Data;

namespace SmartSchoolWebAPI.Migrations
{
    [DbContext(typeof(SmartContext))]
    [Migration("20250423165208_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("SmartSchoolWebAPI.model.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataDeEncerramento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeMatricula")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Matricula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(6565),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(7346),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(7382),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(7386),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 4,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(7389),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(7394),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(7396),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataDeFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataDeFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Nota")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8225)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8443)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8462)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8463)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8463)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8465)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8466)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8467)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8468)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8469)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8470)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8471)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8472)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8472)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8473)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8474)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8475)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8476)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8477)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8478)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8479)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8479)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            DataDeInicio = new DateTime(2025, 4, 23, 13, 52, 8, 178, DateTimeKind.Local).AddTicks(8480)
                        });
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sistemas de Informaçãoo"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreRequisitoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PreRequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 6,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 9,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataDeEncerramento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Registro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataDeRegistro = new DateTime(2025, 4, 23, 13, 52, 8, 176, DateTimeKind.Local).AddTicks(4133),
                            Nome = "Lauro",
                            Registro = 1,
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataDeRegistro = new DateTime(2025, 4, 23, 13, 52, 8, 176, DateTimeKind.Local).AddTicks(9547),
                            Nome = "Roberto",
                            Registro = 2,
                            Sobrenome = "Soares"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataDeRegistro = new DateTime(2025, 4, 23, 13, 52, 8, 176, DateTimeKind.Local).AddTicks(9579),
                            Nome = "Ronaldo",
                            Registro = 3,
                            Sobrenome = "Marconi"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataDeRegistro = new DateTime(2025, 4, 23, 13, 52, 8, 176, DateTimeKind.Local).AddTicks(9581),
                            Nome = "Rodrigo",
                            Registro = 4,
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataDeRegistro = new DateTime(2025, 4, 23, 13, 52, 8, 176, DateTimeKind.Local).AddTicks(9582),
                            Nome = "Alexandre",
                            Registro = 5,
                            Sobrenome = "Montanha"
                        });
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.AlunoCurso", b =>
                {
                    b.HasOne("SmartSchoolWebAPI.model.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchoolWebAPI.model.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchoolWebAPI.model.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchoolWebAPI.model.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.Disciplina", b =>
                {
                    b.HasOne("SmartSchoolWebAPI.model.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchoolWebAPI.model.Disciplina", "PreRequisito")
                        .WithMany()
                        .HasForeignKey("PreRequisitoId");

                    b.HasOne("SmartSchoolWebAPI.model.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
