// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchoolWebAPI.Data;

namespace SmartSchoolWebAPI.Migrations
{
    [DbContext(typeof(SmartContext))]
    [Migration("20250715000146_initMySql")]
    partial class initMySql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartSchoolWebAPI.model.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataDeEncerramento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDeMatricula")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(4798),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(5470),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(5505),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(5509),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 4,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(5512),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(5516),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataDeMatricula = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(5519),
                            DataDeNascimento = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDeFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDeFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6171)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6335)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6442)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6445)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6446)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6448)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6449)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6450)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6451)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6452)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6453)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6454)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6455)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6456)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6457)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6457)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6458)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6460)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6460)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6461)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6462)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6463)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            DataDeInicio = new DateTime(2025, 7, 14, 21, 1, 45, 683, DateTimeKind.Local).AddTicks(6464)
                        });
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sistemas de Informaçãoo"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("PreRequisitoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PreRequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 6,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 9,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataDeEncerramento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Registro")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataDeRegistro = new DateTime(2025, 7, 14, 21, 1, 45, 681, DateTimeKind.Local).AddTicks(2932),
                            Nome = "Lauro",
                            Registro = 1,
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataDeRegistro = new DateTime(2025, 7, 14, 21, 1, 45, 681, DateTimeKind.Local).AddTicks(7856),
                            Nome = "Roberto",
                            Registro = 2,
                            Sobrenome = "Soares"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataDeRegistro = new DateTime(2025, 7, 14, 21, 1, 45, 681, DateTimeKind.Local).AddTicks(7900),
                            Nome = "Ronaldo",
                            Registro = 3,
                            Sobrenome = "Marconi"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataDeRegistro = new DateTime(2025, 7, 14, 21, 1, 45, 681, DateTimeKind.Local).AddTicks(7901),
                            Nome = "Rodrigo",
                            Registro = 4,
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataDeRegistro = new DateTime(2025, 7, 14, 21, 1, 45, 681, DateTimeKind.Local).AddTicks(7902),
                            Nome = "Alexandre",
                            Registro = 5,
                            Sobrenome = "Montanha"
                        });
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.AlunoCurso", b =>
                {
                    b.HasOne("SmartSchoolWebAPI.model.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchoolWebAPI.model.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchoolWebAPI.model.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchoolWebAPI.model.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchoolWebAPI.model.Disciplina", b =>
                {
                    b.HasOne("SmartSchoolWebAPI.model.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchoolWebAPI.model.Disciplina", "PreRequisito")
                        .WithMany()
                        .HasForeignKey("PreRequisitoId");

                    b.HasOne("SmartSchoolWebAPI.model.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
